_welcome:
    pattern:  /
    defaults: { _controller: HelperBundle:Default:showMainPage }
    
UserBundle:
    resource: "@UserBundle/Controller/"
    prefix: /
    
NotificationBundle:
    resource: "@NotificationBundle/Controller/"
    prefix: /
    
AdminBundle:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
MarketResearchBundle:
    resource: "@MarketResearchBundle/Controller/"
    type:     annotation
    prefix:   /
    
UserMessagesBundle:
    resource: "@UserMessagesBundle/Controller/"
    type:     annotation
    prefix:   /messages
    
PurchaseBundle:
    resource: "@PurchaseBundle/Controller/"
    type:     annotation
    prefix:   /

HelperBundle:
    resource: "@HelperBundle/Controller/"
    type:     annotation
    prefix:   /
    
DashboardBundle:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

PostBundle:
    resource: "@PostBundle/Controller/"
    type:     annotation
    prefix:   /
    
CatalogBundle:
    resource: "@CatalogBundle/Controller/"
    type:     annotation
    prefix:   /

geo:
    resource: "@GeoBundle/Resources/config/routing.yml"
    prefix:   /geo

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
    
# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
_imagine:
    resource: .
    type:     imagine