parameters:
    notification.class: SP\NotificationBundle\Services\NotificationService

services:
    notification:
        class: %notification.class%
        arguments: [@doctrine.odm.mongodb.document_manager]
      
